@startuml

class owner {
  child  : child
  family  : array<partner|father|mother|child>

}
owner -- child  :  child
owner 0-- partner  :  family
owner 0-- father  :  family
owner 0-- mother  :  family
owner 0-- child  :  family

class partner {
  name  : string

}

class child {
  name * : string

}

class parent {
  name * : string

}

class father {
  age  : integer

}
parent <|-- father

class mother {

}
parent <|-- mother
@enduml
